// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyAYw8qQ4xiMxXuuB75sYH69oOYPRL6Nw',
    appId: '1:407157077877:web:1682d3f12a5b60e657c53c',
    messagingSenderId: '407157077877',
    projectId: 'onboardx-73b02',
    authDomain: 'onboardx-73b02.firebaseapp.com',
    storageBucket: 'onboardx-73b02.firebasestorage.app',
    measurementId: 'G-DKD448CNXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8SB_35XKiL1geubV_rLQv6jxFoY0r-o0',
    appId: '1:407157077877:android:cfade3e026a3a79f57c53c',
    messagingSenderId: '407157077877',
    projectId: 'onboardx-73b02',
    storageBucket: 'onboardx-73b02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgQaWr_KPD4phANuIfzz-RNWjmFSLeyVM',
    appId: '1:407157077877:ios:23240d27e8c56f2c57c53c',
    messagingSenderId: '407157077877',
    projectId: 'onboardx-73b02',
    storageBucket: 'onboardx-73b02.firebasestorage.app',
    iosBundleId: 'com.example.onboardxApp',
  );
}
